version: '3.8'

services:
  db:
    image: mysql:8.0.41-bookworm
    container_name: myone
    ports:
      - "0.0.0.0:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Kyle9907!
      MYSQL_DATABASE: onestack
      MYSQL_USER: kyle
      MYSQL_PASSWORD: Kyle9907!
    networks:
      - onestack-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: onestack
    ports:
      - "1234:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /usr/share/nginx/html/images:/usr/share/nginx/html/images
    networks:
      - onestack-network

networks:
  onestack-network:
    driver: bridge

volumes:
  mysql_data:
