version: '3.8'

services:
  db:
    image: mysql:8.0.41-bookworm
    container_name: myone
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Kyle9907!
      MYSQL_DATABASE: onestack
      MYSQL_USER: kyle
      MYSQL_PASSWORD: Kyle9907!
    networks:
      - onestack-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 20s  # 20초마다 체크
      timeout: 10s   # 10초 대기
      retries: 10    # 10번 재시도
      start_period: 30s  # 컨테이너 시작 후 30초 기다림
    restart: always  # 컨테이너가 죽으면 자동 재시작

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    container_name: onestack
    ports:
      - "1234:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /usr/share/nginx/html/images:/usr/share/nginx/html/images
    networks:
      - onestack-network
    environment:
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      GMAIL_USERNAME: ${GMAIL_USERNAME}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      PORTONE_API_KEY: ${PORTONE_API_KEY}
      PORTONE_API_SECRET: ${PORTONE_API_SECRET}

networks:
  onestack-network:
    driver: bridge

volumes:
  mysql_data:
