version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: myone
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onestack
      MYSQL_USER: kyle
      MYSQL_PASSWORD: Kyle9907!
    networks:
      - onestack-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onestack
    ports:
      - "1234:8080"
    volumes:
      - ./src/main/resources/static:/app/static
    depends_on:
      db:
        condition: service_healthy
    networks:
      - onestack-network

networks:
  onestack-network:
    driver: bridge

volumes:
  mysql_data:
  image_data:
  
